title:
  Gabriel N. Camargo-Toledo
description:
  'The way to cope with the future is to create it.' Ilya Prigogine (maybe)
remote_theme:
  pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  is_project_page: false
